const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const documentEvents={};const ctx={window:{addEventListener(){}},document:{querySelector(){return null},getElementById(){return null},addEventListener(event,fn){(documentEvents[event]??=[]).push(fn)}},requestAnimationFrame(){},setInterval(){},navigator:{},console};vm.createContext(ctx);
for(const file of ['route-guidance.js','map-readiness.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',file),'utf8'),ctx,{filename:file});
const g=ctx.window.FIELD_GUIDANCE,r=ctx.window.FIELD_MAP_READINESS;
assert.equal(g.isLivePosition({lat:44,lon:-73,source:'PHONE GNSS',timestamp:Date.now(),accuracy:10}),true);
for(const p of [{source:'DEMO GNSS',timestamp:Date.now()},{source:'PHONE GNSS',timestamp:Date.now()-180000},{source:'PHONE GNSS',timestamp:Date.now(),accuracy:500},{source:'PHONE GNSS',timestamp:Date.now(),accuracy:'500'},{source:'PHONE GNSS',timestamp:Date.now(),accuracy:-1},{source:'PHONE GNSS',timestamp:Date.now(),accuracy:'invalid'}])assert.equal(g.isLivePosition({lat:44,lon:-73,...p}),false);
assert.equal(g.isLivePosition({lat:44,lon:-73,source:'PHONE GNSS',timestamp:Date.now(),accuracy:'10'}),true);
const sections=[{name:'Long Trail',surface:'dirt',distanceM:100},{name:' long  trail ',surface:'rock',distanceM:200},{label:'UNNAMED OSM PATH',distanceM:25},{name:'Long Trail',distanceM:100},{name:'Side Trail',distanceM:300},{distanceM:150},{name:'Side Trail',distanceM:100}];
const groups=g.continuity(sections);assert.equal(groups.length,4);assert.equal(groups[0].distanceM,425);assert.equal(groups[0].connectorM,25);assert.equal(groups[0].sectionCount,4);assert.equal(groups[1].startM,425);assert.equal(groups[2].name,null);assert.equal(groups[3].startM,875);
assert.equal(g.continuity([{name:'A',distanceM:100},{distanceM:20},{name:'B',distanceM:100}]).length,3);
assert.equal(g.continuity([{name:'A',distanceM:100},{distanceM:60},{name:'A',distanceM:100}]).length,3);
assert.equal(g.continuity([{distanceM:NaN},null]).length,0);
console.log('PASS continuity merges surface changes and labels short matching-name connectors without relabeling different trails');
const a={id:'a',lat:44,lon:-73},b={id:'b',lat:44.001,lon:-73},c={id:'c',lat:44.002,lon:-73},d={id:'d',lat:44.001,lon:-72.999};
const edge=(to,name)=>({to,tags:{name}});
const graph={nodes:new Map([a,b,c,d].map(p=>[p.id,p])),adj:new Map([['a',[edge('b','Long Trail')]],['b',[edge('a','Long Trail'),edge('c','Long Trail'),edge('d','Side Trail'),edge('d','Duplicate')]],['c',[edge('b','Long Trail')]],['d',[edge('b','Side Trail')]]])};
const js=g.junctionsForPath(graph,[a,b,c],[{name:'Long Trail'},{name:'Long Trail'}]);assert.equal(js.length,1);assert.equal(js[0].degree,3);assert.equal(js[0].alternatives.length,1);assert.equal(js[0].nextId,'c');assert.ok(js[0].distanceM>110&&js[0].distanceM<112);
const plan={points:[a,c],junctions:js};const close=g.next(plan,{lat:44.0005,lon:-73});assert.equal(close.near,true);assert.ok(close.distanceToM>55&&close.distanceToM<57);assert.equal(g.next(plan,{lat:44.0005,lon:-73.01}).near,false);assert.equal(g.next(plan,{lat:44.0018,lon:-73}),null);assert.equal(g.next(plan,{lat:null,lon:null}),null);
const first={points:[a,b],junctions:g.junctionsForPath(graph,[a,b],[{name:'Long Trail'}])};const second={points:[b,d],junctions:g.junctionsForPath(graph,[b,d],[{name:'Side Trail'}])};const joined=g.combine([{result:first},{result:second}]);assert.equal(joined.length,1);assert.equal(joined[0].previousId,'a');assert.equal(joined[0].nextId,'d');assert.equal(joined[0].alternatives.length,1);assert.equal(joined[0].alternatives[0].nodeId,'c');
const reversed=g.reverseLeg({...first,trailSections:sections,startSnap:a,endSnap:b});assert.equal(reversed.points[0].id,'b');assert.equal(reversed.junctions[0].distanceM,0);assert.equal(reversed.junctions[0].nextId,'a');assert.equal(reversed.junctions[0].outgoing,'Long Trail');
console.log('PASS actual graph junctions, duplicate-edge filtering, along-route proximity, off-route suppression, leg-boundary joining and reverse guidance');
const routePoints=Array.from({length:1001},(_,i)=>({lat:44+i*.00001,lon:-73+.00002*Math.sin(i/20)}));
const position={lat:44.0053,lon:-73+.00002*Math.sin(530/20)+.00003};
let referenceOffset=Infinity,referenceProgress=0,cumulative=0;
for(let i=1;i<routePoints.length;i++){
 const a=routePoints[i-1],b=routePoints[i],scale=Math.cos(position.lat*Math.PI/180),x=(b.lon-a.lon)*scale,y=b.lat-a.lat;
 const t=Math.max(0,Math.min(1,((position.lon-a.lon)*scale*x+(position.lat-a.lat)*y)/(x*x+y*y||1)));
 const off=g.length([position,{lat:a.lat+t*(b.lat-a.lat),lon:a.lon+t*(b.lon-a.lon)}]),distance=g.length([a,b]);
 if(off<referenceOffset){referenceOffset=off;referenceProgress=cumulative+t*distance}
 cumulative+=distance;
}
const projected=g.project(routePoints,position);assert.ok(Math.abs(projected.offsetM-referenceOffset)<1e-7);assert.ok(Math.abs(projected.progressM-referenceProgress)<1e-7);
const projectedAgain=g.project(routePoints,{...position,lat:position.lat+.00001});assert.ok(projectedAgain.progressM>0);
console.log('PASS cached junction route-segments preserve long-route projection results');

const nodes=new Map();
const node=()=>{let html='',writes=0;return {get innerHTML(){return html},set innerHTML(v){html=v;writes++},get writes(){return writes},textContent:'',classList:{toggle(){}}}};
for(const id of ['trailContinuityRows','junctionRows','junctionPanel','junctionState','junctionInstruction','junctionDetail'])nodes.set(id,node());
ctx.document.getElementById=id=>nodes.get(id)||null;
let livePos={lat:44.0003,lon:-73,source:'PHONE GNSS',timestamp:Date.now(),accuracy:8};
let activePlan={updatedAt:'stable',points:[a,b,c],junctions:js,trailSections:[{name:'Original Trail',distanceM:220}]};
ctx.window.FIELD_ROUTE_STATE={getPlan:()=>({...activePlan,points:activePlan.points.map(p=>({...p}))}),current:()=>livePos};
const firstRender=g.render();assert.ok(firstRender.cue);
livePos={...livePos,lat:44.0006,timestamp:Date.now()};
const secondRender=g.render();assert.ok(secondRender.cue.distanceToM<firstRender.cue.distanceToM);
assert.equal(nodes.get('trailContinuityRows').writes,1);assert.equal(nodes.get('junctionRows').writes,1);
activePlan={...activePlan,trailSections:[{name:'Updated Trail',distanceM:220}]};
documentEvents['fieldos:routemetadatachange'][0]();g.render();
assert.equal(nodes.get('trailContinuityRows').writes,2);assert.match(nodes.get('trailContinuityRows').innerHTML,/Updated Trail/);
assert.equal(nodes.get('junctionRows').writes,2);
console.log('PASS live junction distance updates without rewriting static trail/junction DOM; metadata changes invalidate the cache');
const MB=1048576;assert.equal(r.assess(0).allowed,false);assert.equal(r.assess(-1).allowed,false);assert.equal(r.assess(251*MB).allowed,false);assert.equal(r.assess(20*MB,{quota:100*MB,usage:80*MB}).allowed,false);assert.equal(r.assess(20*MB,{quota:100*MB,usage:60*MB}).allowed,true);assert.equal(r.assess(20*MB,{}).known,false);assert.equal(r.assess(20*MB,{}).allowed,true);assert.equal(r.assess(20*MB,{quota:0,usage:0}).known,false);
assert.equal(r.age('not a date'),'UNKNOWN');assert.equal(r.age(new Date(Date.now()+86400000).toISOString()),'UNKNOWN');const info=r.packInfo({name:'Map',source:'import',created:'2026-09-28T12:00:00Z',bounds:[-74,43,-72,45]},Date.parse('2026-09-30T12:00:00Z'));assert.equal(info.savedAge,'2 DAYS');assert.equal(info.dataDate,'UNKNOWN');assert.match(info.coverage,/43.000/);
console.log('PASS capacity/headroom limits, unavailable quota, future dates and separation of saved age from source-data age');
(async()=>{ctx.navigator.storage={estimate:async()=>({quota:100*MB,usage:90*MB})};await assert.rejects(r.preflight(20*MB),/Not enough/);ctx.navigator.storage.estimate=async()=>{throw Error('Denied')};assert.equal((await r.preflight(20*MB)).known,false);console.log('PASS asynchronous storage checks block insufficient quota and recover from unavailable estimates')})().catch(e=>{console.error(e);process.exitCode=1});
