// Behavioral tests for retained UI/map rendering, independent of live tile servers.
const {JSDOM}=require('jsdom');
const fs=require('node:fs'),assert=require('node:assert/strict');
const dom=new JSDOM('<div class="view active" id="home"><div id="homeRealMap"></div></div><div id="cards"></div>',{url:'https://field.test',runScripts:'outside-only',pretendToBeVisual:true});
const w=dom.window,d=w.document;
w.HTMLElement.prototype.getBoundingClientRect=()=>({width:390,height:360,left:0,top:0,right:390,bottom:360});
w.eval(fs.readFileSync('runtime.js','utf8'));
w.eval(fs.readFileSync('map-engine.js','utf8'));
(async()=>{try{
 const cards=d.getElementById('cards');
 w.FIELD_RUNTIME.patch(cards,'<button data-readiness-id="gps"><b>GPS</b><span>Waiting</span></button><button data-readiness-id="route">Route</button>');
 const gps=cards.firstChild,route=cards.lastChild;gps.focus();let clicks=0;gps.addEventListener('click',()=>clicks++);
 w.FIELD_RUNTIME.patch(cards,'<button data-readiness-id="route">Route ready</button><button class="ok" data-readiness-id="gps"><b>GPS</b><span>Complete</span></button>');
 assert.equal(cards.firstChild,route);assert.equal(cards.lastChild,gps);assert.equal(gps.querySelector('span').textContent,'Complete');assert.equal(d.activeElement,gps);gps.click();assert.equal(clicks,1);
 w.FIELD_RUNTIME.patch(cards,'<p>No checks</p>');assert.equal(cards.childNodes.length,1);assert.equal(cards.firstChild.tagName,'P');
 console.log('PASS keyed UI updates preserve controls, focus, listeners, and ordering');
 const engine=w.FIELD_MAP_ENGINE;
 const st=engine.mount('homeRealMap',{center:{lat:44.4759,lon:-73.2121},zoom:14});
 engine.setView('homeRealMap',{lat:44.4759,lon:-73.2121},14);
 const before=[...st.tiles.values()];assert.ok(before.length>10);
 before.forEach(t=>t.img.onload?.());
 const tile=before.find(t=>t.cls==='native-osm-base'),left=parseFloat(tile.img.style.left);
 engine.setView('homeRealMap',{lat:44.4759,lon:-73.2120},14);
 assert.ok(st.tiles.has([...st.tiles].find(([,v])=>v===tile)[0]));
 assert.ok(Math.abs(parseFloat(tile.img.style.left)-left)>1,'Small pans reposition retained raster images');
 assert.ok(before.every(t=>[...st.tiles.values()].includes(t)),'Subtile pan reuses tile nodes');
 const smallPanCount=st.tiles.size;
 engine.setView('homeRealMap',{lat:44.4759,lon:-73.2120},14.1);
 assert.ok([...st.tiles.values()].every(t=>before.includes(t)),'Fractional zoom preserves existing tile nodes');
 assert.match(st.base.style.transform,/scale/);
 engine.setView('homeRealMap',{lat:44.4759,lon:-73.2120},15);
 assert.ok([...st.tiles.values()].some(t=>t.z===14&&t.status==='loaded'),'Loaded lower zoom remains during tile loading');
 [...st.tiles.values()].filter(t=>t.z===15).forEach(t=>t.img.onload?.());
 assert.ok([...st.tiles.values()].every(t=>t.z===15),'Fallback is retired after replacement loads');
 for(let i=0;i<40;i++)engine.setView('homeRealMap',{lat:44.4759,lon:-73.2120+i*.004},15);
 assert.ok(st.tiles.size<smallPanCount*3,'Repeated panning has bounded tile DOM');
 const tiles=[...st.tiles.values()];engine.unmount('homeRealMap');
 assert.equal(st.tiles.size,0);assert.ok(tiles.every(t=>t.img.onload===null&&t.img.onerror===null));assert.equal(d.getElementById('homeRealMap').childElementCount,0);
 console.log('PASS exact small-pan positioning, fractional tile reuse, zoom fallback, bounded tile lifetime, and teardown');
}finally{dom.window.close();}})().catch(e=>{console.error(e);process.exitCode=1});
