// Behavioral tests for retained UI/map rendering, independent of live tile servers.
const {JSDOM}=require('jsdom');
const fs=require('node:fs'),assert=require('node:assert/strict');
const dom=new JSDOM('<div class="view active" id="home"><div id="homeRealMap"></div></div><div id="cards"></div>',{url:'https://field.test',runScripts:'outside-only',pretendToBeVisual:true});
const w=dom.window,d=w.document;
w.HTMLElement.prototype.getBoundingClientRect=()=>({width:390,height:360,left:0,top:0,right:390,bottom:360});
w.eval(fs.readFileSync('runtime.js','utf8'));
w.eval(fs.readFileSync('map-engine.js','utf8'));
(async()=>{try{
 const cards=d.getElementById('cards');
 w.FIELD_RUNTIME.patch(cards,'<button data-readiness-id="gps"><b>GPS</b><span>Waiting</span></button><button data-readiness-id="route">Route</button>');
 const gps=cards.firstChild,route=cards.lastChild;gps.focus();let clicks=0;gps.addEventListener('click',()=>clicks++);
 w.FIELD_RUNTIME.patch(cards,'<button data-readiness-id="route">Route ready</button><button class="ok" data-readiness-id="gps"><b>GPS</b><span>Complete</span></button>');
 assert.equal(cards.firstChild,route);assert.equal(cards.lastChild,gps);assert.equal(gps.querySelector('span').textContent,'Complete');assert.equal(d.activeElement,gps);gps.click();assert.equal(clicks,1);
 w.FIELD_RUNTIME.patch(cards,'<p>No checks</p>');assert.equal(cards.childNodes.length,1);assert.equal(cards.firstChild.tagName,'P');
 console.log('PASS keyed UI updates preserve controls, focus, listeners, and ordering');
 const engine=w.FIELD_MAP_ENGINE;
 const st=engine.mount('homeRealMap',{center:{lat:44.4759,lon:-73.2121},zoom:14});
 engine.setView('homeRealMap',{lat:44.4759,lon:-73.2121},14);
 const before=[...st.tiles.values()];assert.ok(before.length>10);
 before.forEach(t=>t.img.onload?.());
 const tile=before.find(t=>t.cls==='native-osm-base'),left=parseFloat(tile.img.style.left);
 engine.setView('homeRealMap',{lat:44.4759,lon:-73.2120},14);
 assert.ok(st.tiles.has([...st.tiles].find(([,v])=>v===tile)[0]));
 assert.ok(Math.abs(parseFloat(tile.img.style.left)-left)>1,'Small pans reposition retained raster images');
 assert.ok(before.every(t=>[...st.tiles.values()].includes(t)),'Subtile pan reuses tile nodes');
 const smallPanCount=st.tiles.size;
 engine.setView('homeRealMap',{lat:44.4759,lon:-73.2120},14.1);
 assert.ok([...st.tiles.values()].every(t=>before.includes(t)),'Fractional zoom preserves existing tile nodes');
 assert.match(st.base.style.transform,/scale/);
 engine.setView('homeRealMap',{lat:44.4759,lon:-73.2120},15);
 assert.ok([...st.tiles.values()].some(t=>t.z===14&&t.status==='loaded'),'Loaded lower zoom remains during tile loading');
 [...st.tiles.values()].filter(t=>t.z===15).forEach(t=>t.img.onload?.());
 assert.ok([...st.tiles.values()].every(t=>t.z===15),'Fallback is retired after replacement loads');
 for(let i=0;i<40;i++)engine.setView('homeRealMap',{lat:44.4759,lon:-73.2120+i*.004},15);
 assert.ok(st.tiles.size<smallPanCount*3,'Repeated panning has bounded tile DOM');
 // Camera and GPS redraws should reuse planned route data until it changes.
 let routeReads=0,activeRoute=[{lat:44.4759,lon:-73.2121},{lat:44.4761,lon:-73.2119}];
 w.FIELD_ROUTE_STATE={getPoints(){routeReads++;return activeRoute.map(p=>({...p}))}};
 d.dispatchEvent(new w.CustomEvent('fieldos:routechange'));
 engine.setView('homeRealMap',{lat:44.4759,lon:-73.2121},14);
 engine.setView('homeRealMap',{lat:44.4759,lon:-73.2120},14);
 assert.equal(routeReads,1,'repainting the map should reuse cached route points');
 activeRoute=[{lat:44.4759,lon:-73.2121},{lat:44.4765,lon:-73.2119}];
 d.dispatchEvent(new w.CustomEvent('fieldos:routechange'));
 assert.equal(routeReads,2,'route changes must invalidate route point cache');
 console.log('PASS planned route points are reused between map paints and refreshed on route edits');
 // Hidden map overlays should not rebuild for GPS/track events, but must catch up on entry.
 const hidden=d.createElement('div');hidden.id='map';hidden.className='view';hidden.innerHTML='<div id="realMap"></div>';d.body.appendChild(hidden);
 const inactive=engine.mount('realMap',{center:{lat:44.4759,lon:-73.2121},zoom:14});
 engine.setView('realMap',{lat:44.4759,lon:-73.2121},14);
 let tracked=[{lat:44.4759,lon:-73.2121},{lat:44.4761,lon:-73.2119}],trackReads=0,waypointReads=0;
 w.FIELD_MAP_DATA={track:()=>{trackReads++;return tracked},waypoints:()=>{waypointReads++;return []}};
 const hiddenBefore=inactive.overlay.innerHTML;
 d.dispatchEvent(new w.CustomEvent('fieldos:trackchange'));
 assert.equal(inactive.overlay.innerHTML,hiddenBefore,'hidden map must not rebuild its overlay on background track updates');
 assert.match(st.overlay.innerHTML,/native-track-line/,'visible Home overlay receives track updates');
 assert.equal(trackReads,1);
 d.dispatchEvent(new w.CustomEvent('fieldos:positionchange'));
 assert.equal(trackReads,1,'GPS updates should not re-clone unchanged track geometry');
 assert.equal(waypointReads,1,'GPS updates should not re-clone unchanged waypoints');
 tracked=[...tracked,{lat:44.4770,lon:-73.2105}];
 d.dispatchEvent(new w.CustomEvent('fieldos:trackchange'));
 assert.equal(trackReads,2,'track events must invalidate cached track data');
 w.FIELD_MAP_DATA={track:()=>{trackReads++;return tracked},waypoints:()=>[]};
 d.dispatchEvent(new w.CustomEvent('fieldos:positionchange'));
 assert.equal(trackReads,3,'replacing the map data bridge must invalidate cached track data');
 let onGeoFix=null;
 Object.defineProperty(w.navigator,'geolocation',{configurable:true,value:{watchPosition(cb){onGeoFix=cb;return 1},clearWatch(){}}});
 engine.startLiveLocation();
 const hiddenBeforeGps=inactive.overlay.innerHTML;
 onGeoFix({coords:{latitude:44.4759,longitude:-73.2121,accuracy:5}});
 assert.equal(inactive.overlay.innerHTML,hiddenBeforeGps,'native GPS fixes must not repaint hidden map overlays');
 assert.match(st.overlay.innerHTML,/native-self-marker/,'visible map displays latest native GPS fix');
 const stableMarker=st.overlay.querySelector('.native-self-marker'),stableRoute=st.overlay.querySelector('.planned-route-line'),stableTrack=st.overlay.querySelector('.native-track-line');
 const beforeX=stableMarker.getAttribute('cx');
 onGeoFix({coords:{latitude:44.47591,longitude:-73.21209,accuracy:5}});
 assert.equal(st.overlay.querySelector('.native-self-marker'),stableMarker,'small GPS changes update the same marker node');
 assert.notEqual(stableMarker.getAttribute('cx'),beforeX,'retained marker must move to latest GPS fix');
 assert.equal(st.overlay.querySelector('.planned-route-line'),stableRoute,'GPS fixes must not rebuild route geometry SVG');
 assert.equal(st.overlay.querySelector('.native-track-line'),stableTrack,'GPS fixes must not rebuild recorded track SVG');
 assert.equal(inactive.overlay.innerHTML,hiddenBeforeGps,'second native GPS fix also leaves hidden map untouched');
 d.getElementById('home').classList.remove('active');hidden.classList.add('active');
 d.dispatchEvent(new w.CustomEvent('fieldos:viewchange',{detail:{view:'map'}}));
 await new Promise(resolve=>w.requestAnimationFrame(()=>w.requestAnimationFrame(resolve)));
 assert.match(inactive.overlay.innerHTML,/native-track-line/,'map entry must render current track data');
 assert.match(inactive.overlay.innerHTML,/native-self-marker/,'hidden map displays latest native GPS fix on entry');
 engine.stopLiveLocation();
 engine.unmount('realMap');hidden.remove();d.getElementById('home').classList.add('active');
 console.log('PASS offscreen map overlays skip background updates and refresh when opened');
 const tiles=[...st.tiles.values()];engine.unmount('homeRealMap');
 assert.equal(st.tiles.size,0);assert.ok(tiles.every(t=>t.img.onload===null&&t.img.onerror===null));assert.equal(d.getElementById('homeRealMap').childElementCount,0);
 console.log('PASS exact small-pan positioning, fractional tile reuse, zoom fallback, bounded tile lifetime, and teardown');
}finally{dom.window.close();}})().catch(e=>{console.error(e);process.exitCode=1});
