// Behavioral tests for retained UI/map rendering, independent of live tile servers.
const {JSDOM}=require('jsdom');
const fs=require('node:fs'),assert=require('node:assert/strict');
const dom=new JSDOM('<div class="view active" id="home"><div id="homeRealMap"></div></div><div class="view" id="map"><div id="realMap"></div></div><div id="cards"></div>',{url:'https://field.test',runScripts:'outside-only',pretendToBeVisual:true});
const w=dom.window,d=w.document;
w.HTMLElement.prototype.getBoundingClientRect=()=>({width:390,height:360,left:0,top:0,right:390,bottom:360});
w.eval(fs.readFileSync('runtime.js','utf8'));
w.eval(fs.readFileSync('map-engine.js','utf8'));
(async()=>{try{
 const cards=d.getElementById('cards');
 w.FIELD_RUNTIME.patch(cards,'<button data-readiness-id="gps"><b>GPS</b><span>Waiting</span></button><button data-readiness-id="route">Route</button>');
 const gps=cards.firstChild,route=cards.lastChild;gps.focus();let clicks=0;gps.addEventListener('click',()=>clicks++);
 w.FIELD_RUNTIME.patch(cards,'<button data-readiness-id="route">Route ready</button><button class="ok" data-readiness-id="gps"><b>GPS</b><span>Complete</span></button>');
 assert.equal(cards.firstChild,route);assert.equal(cards.lastChild,gps);assert.equal(gps.querySelector('span').textContent,'Complete');assert.equal(d.activeElement,gps);gps.click();assert.equal(clicks,1);
 w.FIELD_RUNTIME.patch(cards,'<p>No checks</p>');assert.equal(cards.childNodes.length,1);assert.equal(cards.firstChild.tagName,'P');
 console.log('PASS keyed UI updates preserve controls, focus, listeners, and ordering');
 const engine=w.FIELD_MAP_ENGINE;
 const st=engine.mount('homeRealMap',{center:{lat:44.4759,lon:-73.2121},zoom:14});
 engine.setView('homeRealMap',{lat:44.4759,lon:-73.2121},14);
 const before=[...st.tiles.values()];assert.ok(before.length>10);
 before.forEach(t=>t.img.onload?.());
 const tile=before.find(t=>t.cls==='native-osm-base'),left=parseFloat(tile.img.style.left);
 engine.setView('homeRealMap',{lat:44.4759,lon:-73.2120},14);
 assert.ok(st.tiles.has([...st.tiles].find(([,v])=>v===tile)[0]));
 assert.ok(Math.abs(parseFloat(tile.img.style.left)-left)>1,'Small pans reposition retained raster images');
 assert.ok(before.every(t=>[...st.tiles.values()].includes(t)),'Subtile pan reuses tile nodes');
 const smallPanCount=st.tiles.size;
 engine.setView('homeRealMap',{lat:44.4759,lon:-73.2120},14.1);
 assert.ok([...st.tiles.values()].every(t=>before.includes(t)),'Fractional zoom preserves existing tile nodes');
 assert.match(st.base.style.transform,/scale/);
 engine.setTerrain(true);
 const firstShade=[...st.tiles.values()].filter(v=>v.cls==='native-terrain-tile');
 assert.ok(firstShade.length>0,'hillshade requests tiles when first enabled');
 firstShade.forEach(v=>v.img.onload?.());
 const centerTileX=Math.floor((-73.2120+180)/360*2**14),sinLat=Math.sin(44.4759*Math.PI/180);
 const centerTileY=Math.floor((.5-Math.log((1+sinLat)/(1-sinLat))/(4*Math.PI))*2**14);
 const shaded=firstShade.find(v=>v.x===centerTileX&&v.y===centerTileY);
 assert.ok(shaded,'test selects the actual visible center tile, not a prefetched margin tile');
 const shadeKey=[...st.tiles].find(([,v])=>v===shaded)[0];
 const oldLeft=shaded.img.style.left,shadeSrc=shaded.img.src,oldTransform=st.terrainTiles.style.transform;
 engine.setView('homeRealMap',{lat:44.4759,lon:-73.21198},14.1);
 assert.equal(st.tiles.get(shadeKey),shaded,'small pan keeps loaded terrain tiles');
 assert.equal(shaded.img.style.left,oldLeft,'panning keeps terrain tile images at fixed coordinates');
 assert.equal(shaded.img.src,shadeSrc,'panning does not request terrain imagery twice');
 assert.notEqual(st.terrainTiles.style.transform,oldTransform,'panning moves one compositor-shaded tile atlas');
 engine.setView('homeRealMap',{lat:44.4759,lon:-73.2120},16);
 assert.ok([...st.tiles.values()].some(t=>t.z===14&&t.status==='loaded'),'Rapid two-level zoom retains old base until replacement loads');
 assert.ok(st.tiles.has(shadeKey),'visible old hillshade remains during fast raster zoom');
 const newShades=[...st.tiles.values()].filter(v=>v.cls==='native-terrain-tile'&&v.z===16);
 assert.ok(newShades.length>0,'new hillshade requested at new raster zoom');
 newShades.forEach(v=>v.img.onload?.());
 assert.ok(st.tiles.has(shadeKey),'decoded hillshade keeps previous frame until the browser paints the replacement');
 await new Promise(resolve=>w.requestAnimationFrame(()=>w.requestAnimationFrame(()=>w.requestAnimationFrame(resolve))));
 assert.ok(!st.tiles.has(shadeKey),'old hillshade retires after replacement has painted');
 [...st.tiles.values()].filter(t=>t.z===16).forEach(t=>t.img.onload?.());
 await new Promise(resolve=>w.requestAnimationFrame(()=>w.requestAnimationFrame(()=>w.requestAnimationFrame(resolve))));
 assert.ok([...st.tiles.values()].every(t=>t.z===16),'Fallback retires once replacement imagery has painted');
 engine.setTerrain(false);
 assert.ok(![...st.tiles.values()].some(v=>v.cls==='native-terrain-tile'),'turning terrain off removes the hillshade atlas');
 // Browser wheel burst across an integer raster zoom must never expose
 // an empty pale base while new tile requests are still pending.
 engine.setView('homeRealMap',{lat:44.4759,lon:-73.2120},14.8);
 [...st.tiles.values()].filter(t=>t.z===14).forEach(t=>t.img.onload?.());
 await new Promise(resolve=>w.requestAnimationFrame(()=>w.requestAnimationFrame(()=>w.requestAnimationFrame(resolve))));
 const outgoing=[...st.tiles.values()].filter(t=>t.layer===st.base&&t.z===14&&t.status==='loaded');
 assert.ok(outgoing.length>0,'prior zoom has decoded base tiles');
 for(let i=0;i<3;i++)st.onWheel({ctrlKey:false,deltaY:-60,clientX:190,clientY:170,preventDefault(){}});
 await new Promise(resolve=>setTimeout(resolve,175));
 assert.ok(st.zoom>15,'wheel burst crosses an integer tile boundary');
 assert.ok([...st.tiles.values()].some(t=>t.layer===st.base&&t.z===15&&t.status==='pending'),'higher-resolution imagery requests are still pending');
 assert.ok(outgoing.some(t=>t.img.isConnected),'prior imagery stays visible during pending wheel zoom');
 [...st.tiles.values()].filter(t=>t.layer===st.base&&t.z===15).forEach(t=>t.img.onload?.());
 assert.ok(outgoing.some(t=>t.img.isConnected),'prior imagery stays visible until decoded replacements paint');
 await new Promise(resolve=>w.requestAnimationFrame(()=>w.requestAnimationFrame(()=>w.requestAnimationFrame(resolve))));
 assert.ok(outgoing.every(t=>!t.img.isConnected),'replaced imagery retires after a painted frame, not during wheel preview');
 console.log('PASS desktop wheel bursts keep outgoing base tiles until decoded replacements paint');
 const failing=[...st.tiles.values()].find(t=>t.cls==='native-osm-base');
 const failedKey=[...st.tiles].find(([,tile])=>tile===failing)[0];
 failing.img.onerror?.();assert.equal(failing.status,'error');
 w.dispatchEvent(new w.Event('online'));
 assert.notEqual(st.tiles.get(failedKey),failing,'Reconnect re-requests failed tile without moving camera');
 assert.equal(st.retryCounts.size,0,'Reconnect clears retry budget');
 [...st.tiles.values()].forEach(t=>t.img.onload?.());
 for(let i=0;i<40;i++)engine.setView('homeRealMap',{lat:44.4759,lon:-73.2120+i*.004},16);
 assert.ok(st.tiles.size<smallPanCount*3,'Repeated panning has bounded tile DOM');
 // Camera and GPS redraws should reuse planned route data until edited.
 let routeReads=0,activeRoute=[{lat:44.4759,lon:-73.2121},{lat:44.4761,lon:-73.2119}];
 w.FIELD_ROUTE_STATE={getPoints(){routeReads++;return activeRoute.map(p=>({...p}))}};
 d.dispatchEvent(new w.CustomEvent('fieldos:routechange'));
 engine.setView('homeRealMap',{lat:44.4759,lon:-73.2121},14);
 engine.setView('homeRealMap',{lat:44.4759,lon:-73.2120},14);
 assert.equal(routeReads,1,'map redraws should reuse cached route points');
 activeRoute=[{lat:44.4759,lon:-73.2121},{lat:44.4765,lon:-73.2119}];
 d.dispatchEvent(new w.CustomEvent('fieldos:routechange'));
 assert.equal(routeReads,2,'route edits must invalidate cached route points');
 console.log('PASS planned route geometry is cached and invalidates after route edits');
 // Route difficulty shading was previously present only inside Route Planner.
 // Assert that an existing DEM profile also grades the visible Home/Terrain map.
 const gradedPoints=[0,1,2,3].map(i=>({lat:44.4759+i*.0009,lon:-73.2121}));
 const gradeStep=6371000*(.0009*Math.PI/180);
 const gradedSamples=gradedPoints.map((p,i)=>({...p,distanceM:i*gradeStep,elevationFt:500+i*45}));
 w.FIELD_ROUTE_SLOPE={
   gradeAtDistance(_profile,distanceM){return distanceM<90?2:distanceM<200?10:18},
   slopeClass(grade){return {key:grade>=15?'hard':grade>=8?'medium':'easy'}}
 };
 w.FIELD_ROUTE_STATE={getPoints(){return gradedPoints},getPlan(){return {elevationProfile:gradedSamples}}};
 d.dispatchEvent(new w.CustomEvent('fieldos:routechange'));
 assert.ok(st.overlay.querySelector('.planned-route-slope-medium'),'medium sustained grade draws orange planned route on main map');
 assert.ok(st.overlay.querySelector('.planned-route-slope-hard'),'hard sustained grade draws red planned route on main map');
 w.FIELD_ROUTE_STATE={getPoints(){return gradedPoints},getPlan(){return {elevationProfile:gradedSamples.map((p,i)=>({...p,distanceM:i*gradeStep*3}))}}};
 d.dispatchEvent(new w.CustomEvent('fieldos:routechange'));
 assert.equal(st.overlay.querySelectorAll('.planned-route-slope').length,0,'stale elevation profile must not color a different route');
 console.log('PASS overview map restores orange/red sustained-grade sections and refuses mismatched DEM data');

 // Hidden-map telemetry should not redraw offscreen SVG overlays, but
 // navigation into that view must present the latest track data.
 const hidden=d.getElementById('map');
 const inactive=engine.mount('realMap',{center:{lat:44.4759,lon:-73.2121},zoom:14});
 engine.setView('realMap',{lat:44.4759,lon:-73.2121},14);
 let tracked=[{lat:44.4759,lon:-73.2121},{lat:44.4761,lon:-73.2119}],trackReads=0,waypointReads=0;
 w.FIELD_MAP_DATA={track:()=>{trackReads++;return tracked},waypoints:()=>{waypointReads++;return []}};
 const oldOverlay=inactive.overlay.innerHTML;
 d.dispatchEvent(new w.CustomEvent('fieldos:trackchange'));
 assert.equal(inactive.overlay.innerHTML,oldOverlay,'offscreen map does not rebuild for background track events');
 assert.match(st.overlay.innerHTML,/native-track-line/,'visible Home overlay receives track updates');
 assert.equal(trackReads,1);
 d.dispatchEvent(new w.CustomEvent('fieldos:positionchange'));
 assert.equal(trackReads,1,'GPS redraws must reuse cached track geometry');
 assert.equal(waypointReads,1,'GPS redraws must reuse cached waypoints');
 tracked=[...tracked,{lat:44.477,lon:-73.2105}];
 d.dispatchEvent(new w.CustomEvent('fieldos:trackchange'));
 assert.equal(trackReads,2,'track changes invalidate cached track data');
 w.FIELD_MAP_DATA={track:()=>{trackReads++;return tracked},waypoints:()=>[]};
 d.dispatchEvent(new w.CustomEvent('fieldos:positionchange'));
 assert.equal(trackReads,3,'new map-data provider invalidates cached track data');
 let previewReads=0,fullReads=0;
 w.FIELD_MAP_DATA={trackPreview(limit){previewReads++;assert.equal(limit,1500);return tracked},track(){fullReads++;return tracked},waypoints:()=>[]};
 d.dispatchEvent(new w.CustomEvent('fieldos:trackchange'));
 assert.equal(previewReads,1,'native map requests capped track preview');
 assert.equal(fullReads,0,'native map does not clone full track when preview exists');
 let onGeoFix=null;
 Object.defineProperty(w.navigator,'geolocation',{configurable:true,value:{watchPosition(cb){onGeoFix=cb;return 1},clearWatch(){}}});
 engine.startLiveLocation();
 const hiddenBeforeGps=inactive.overlay.innerHTML;
 onGeoFix({coords:{latitude:44.4759,longitude:-73.2121,accuracy:5}});
 assert.equal(inactive.overlay.innerHTML,hiddenBeforeGps,'native GPS must not repaint hidden map overlay');
 assert.match(st.overlay.innerHTML,/native-self-marker/,'Home map displays latest native GPS fix');
 const stableMarker=st.overlay.querySelector('.native-self-marker'),stableRoute=st.overlay.querySelector('.planned-route-line'),stableTrack=st.overlay.querySelector('.native-track-line');
 const beforeX=stableMarker.getAttribute('cx');
 onGeoFix({coords:{latitude:44.47591,longitude:-73.21209,accuracy:5}});
 assert.equal(st.overlay.querySelector('.native-self-marker'),stableMarker,'small GPS changes must retain original marker DOM');
 assert.notEqual(stableMarker.getAttribute('cx'),beforeX,'retained GPS marker must move');
 assert.equal(st.overlay.querySelector('.planned-route-line'),stableRoute,'GPS must not recreate route geometry SVG');
 assert.equal(st.overlay.querySelector('.native-track-line'),stableTrack,'GPS must not recreate recorded track SVG');
 assert.equal(inactive.overlay.innerHTML,hiddenBeforeGps,'hidden map remains untouched after repeat GPS fix');
 // Regression: releasing the main mobile map must not allow the next GPS
 // fix to pull the camera back. Location marker continues updating in place.
 engine.center('homeRealMap');
 assert.equal(engine.getView('homeRealMap').following,true,'Explicit center resumes camera following');
 st.onPointerDown({pointerId:501,button:0,clientX:160,clientY:175,preventDefault(){}});
 st.onPointerMove({pointerId:501,clientX:235,clientY:200});
 st.onPointerUp({pointerId:501,clientX:235,clientY:200});
 const manuallyPanned=engine.getView('homeRealMap');
 assert.equal(manuallyPanned.following,false,'Dragging disables only camera following');
 const markerBeforeFarFix=st.overlay.querySelector('.native-self-marker').getAttribute('cx');
 onGeoFix({coords:{latitude:44.6,longitude:-73.3,accuracy:4}});
 engine.refresh(false);
 assert.deepEqual(engine.getView('homeRealMap').center,manuallyPanned.center,'A GPS fix and passive refresh must preserve a manually panned center');
 assert.notEqual(st.overlay.querySelector('.native-self-marker').getAttribute('cx'),markerBeforeFarFix,'The live GPS marker still updates after manual panning');
 onGeoFix({coords:{latitude:44.61,longitude:-73.31,accuracy:4}});
 assert.deepEqual(engine.getView('homeRealMap').center,manuallyPanned.center,'Repeated GPS fixes must never override manual panning');
 engine.stopLiveLocation();engine.startLiveLocation();
 assert.equal(engine.getView('homeRealMap').following,false,'Turning GPS back on never overrides manual map movement');
 onGeoFix({coords:{latitude:44.615,longitude:-73.315,accuracy:4}});
 assert.deepEqual(engine.getView('homeRealMap').center,manuallyPanned.center,'GPS reactivation preserves manually chosen viewport');
 engine.center('homeRealMap');
 assert.equal(engine.getView('homeRealMap').following,true,'Explicit center re-enables follow when GPS is live');
 onGeoFix({coords:{latitude:44.62,longitude:-73.32,accuracy:4}});
 assert.ok(Math.abs(engine.getView('homeRealMap').center.lat-44.62)<.00001,'Camera follows live GPS again after explicit center');
 engine.zoom('homeRealMap',.5);
 assert.equal(engine.getView('homeRealMap').following,false,'Manual zoom disengages GPS follow');
 const zoomCenter=engine.getView('homeRealMap').center;
 onGeoFix({coords:{latitude:44.7,longitude:-73.4,accuracy:4}});
 assert.deepEqual(engine.getView('homeRealMap').center,zoomCenter,'Zoomed map remains independent of subsequent GPS updates');
 console.log('PASS manual mobile pan/zoom keeps camera stable through GPS updates; recenter explicitly restores following');
 d.getElementById('home').classList.remove('active');hidden.classList.add('active');
 d.dispatchEvent(new w.CustomEvent('fieldos:viewchange',{detail:{view:'map'}}));
 await new Promise(resolve=>w.requestAnimationFrame(()=>w.requestAnimationFrame(resolve)));
 assert.match(inactive.overlay.innerHTML,/native-track-line/,'opening hidden map renders latest track data');
 assert.match(inactive.overlay.innerHTML,/native-self-marker/,'hidden map displays latest GPS fix on entry');
 engine.stopLiveLocation();
 engine.unmount('realMap');hidden.classList.remove('active');d.getElementById('home').classList.add('active');
 console.log('PASS hidden overlays pause on telemetry and catch up on view activation');
 // Android/iOS may interrupt a drag or pinch with pointercancel; preserve
 // its final visible preview instead of restoring the previous camera.
 let cancelledTaps=0;engine.setTapHandler('homeRealMap',()=>cancelledTaps++);
 const beforeCancelDrag=engine.getView('homeRealMap');
 st.onPointerDown({pointerId:401,button:0,clientX:170,clientY:175,preventDefault(){}});
 st.onPointerMove({pointerId:401,clientX:215,clientY:195});
 st.onPointerCancel({pointerId:401,clientX:215,clientY:195});
 const afterCancelDrag=engine.getView('homeRealMap');
 assert.ok(Math.abs(afterCancelDrag.center.lon-beforeCancelDrag.center.lon)>0.0001,'Cancelled drag commits camera translation');
 assert.equal(st.pointers.size,0,'Cancelled gesture releases pointers');
 assert.equal(cancelledTaps,0,'Cancelling a drag cannot tap route editor');
 const beforeCancelPinch=engine.getView('homeRealMap');
 st.onPointerDown({pointerId:402,button:0,clientX:140,clientY:160,preventDefault(){}});
 st.onPointerDown({pointerId:403,button:0,clientX:240,clientY:160,preventDefault(){}});
 st.onPointerMove({pointerId:403,clientX:280,clientY:160});
 st.onPointerCancel({pointerId:403,clientX:280,clientY:160});
 assert.ok(engine.getView('homeRealMap').zoom>beforeCancelPinch.zoom+.4,'Cancelled pinch commits preview zoom');
 assert.equal(st.pointers.size,0);
 assert.equal(cancelledTaps,0,'Cancelled pinch cannot trigger map tap');
 await new Promise(resolve=>w.requestAnimationFrame(()=>w.requestAnimationFrame(resolve)));
 engine.setTapHandler('homeRealMap',null);
 console.log('PASS interrupted mobile drag/pinch preserves camera without phantom taps');
 // Make the older wheel timing test independent of the GPS/manual camera
 // sequence above (which can leave Topo almost at its maximum zoom).
 engine.setView('homeRealMap',{lat:44.4759,lon:-73.2121},14);
 // A throttled rAF must not leave an uncommitted wheel preview on screen.
 const nativeRAF=w.requestAnimationFrame.bind(w),nativeCAF=w.cancelAnimationFrame.bind(w);
 const heldFrames=new Map();let nextFrame=80000;
 w.requestAnimationFrame=callback=>{const id=nextFrame++;heldFrames.set(id,callback);return id};
 w.cancelAnimationFrame=id=>{heldFrames.delete(id)};
 const beforeDeferredWheel=engine.getView('homeRealMap').zoom;
 let wheelPrevented=false;
 st.onWheel({ctrlKey:false,deltaY:-120,clientX:190,clientY:170,preventDefault(){wheelPrevented=true}});
 const delayedId=nextFrame-1;
 assert.ok(heldFrames.has(delayedId),'Wheel paint frame is intentionally delayed');
 await new Promise(resolve=>setTimeout(resolve,170));
 assert.equal(wheelPrevented,true);
 assert.ok(engine.getView('homeRealMap').zoom>beforeDeferredWheel+.15,'Wheel settles despite delayed paint frame');
 assert.equal(heldFrames.has(delayedId),false,'Late preview frame must be cancelled after settle');
 assert.equal(st.wheelDelta,0);
 assert.equal(st.wheelZoom,0);
 w.requestAnimationFrame=nativeRAF;w.cancelAnimationFrame=nativeCAF;
 console.log('PASS delayed wheel frames settle and cancel stale zoom previews');
 w.FIELD_MAP_DATA={trackPreview:()=>[{lat:44.4759,lon:-73.2121,seq:0},
  {lat:44.477,lon:-73.211,seq:20,gapBefore:true},{lat:44.478,lon:-73.210,seq:21}],waypoints:()=>[]};
 d.dispatchEvent(new w.CustomEvent('fieldos:trackchange'));
 engine.setView('homeRealMap',{lat:44.477,lon:-73.211},14);
 assert.ok(st.overlay.querySelector('.native-track-trailhead'),'original trailhead shown as separate marker');
 const clipped=st.overlay.querySelector('.native-track-line');
 assert.ok(clipped&&clipped.getAttribute('points').trim().split(/\s+/).length===2,
  'do not join retained trailhead to missing interior breadcrumb history');
 console.log('PASS track rendering never draws across a missing breadcrumb gap');
 const tiles=[...st.tiles.values()];engine.unmount('homeRealMap');
 assert.equal(st.tiles.size,0);assert.ok(tiles.every(t=>t.img.onload===null&&t.img.onerror===null));assert.equal(d.getElementById('homeRealMap').childElementCount,0);
 assert.equal(d.getElementById('realMap').childElementCount,0,'Hidden Terrain map should not load duplicate tiles');
 w.localStorage.setItem('fieldos-v12-map-source','offline');
 engine.refresh(true);
 d.dispatchEvent(new w.CustomEvent('fieldos:viewchange',{detail:{view:'map'}}));
 await new Promise(resolve=>w.requestAnimationFrame(resolve));
 assert.equal(d.getElementById('realMap').childElementCount,0,'Native map must not overwrite offline renderer');
 assert.equal(d.getElementById('homeRealMap').childElementCount,0,'Offline state must not remount Home');
 w.localStorage.setItem('fieldos-v12-map-source','osm');engine.refresh(true);
 assert.ok(d.getElementById('homeRealMap').childElementCount>0,'Online map remounts on source restoration');
 engine.unmount('homeRealMap');
 console.log('PASS fast zoom fallback, reconnect recovery, hidden-map lazy loading and offline ownership');
}finally{dom.window.close();}})().catch(e=>{console.error(e);process.exitCode=1});
