const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const {JSDOM}=require('jsdom');
const dir=path.resolve(__dirname,'..');
const html=fs.readFileSync(path.join(dir,'index.html'),'utf8');
const app=fs.readFileSync(path.join(dir,'app.js'),'utf8');
const sw=fs.readFileSync(path.join(dir,'sw.js'),'utf8');
const manifest=JSON.parse(fs.readFileSync(path.join(dir,'manifest.webmanifest'),'utf8'));
const safety=fs.readFileSync(path.join(dir,'safety-sync.js'),'utf8');
assert.equal(manifest.start_url,'./index.html','installed PWA should have a stable start URL');
assert.equal(manifest.scope,'./');
assert.ok(sw.includes('safety-sync.js?v=3.83-hotfix1'),'offline shell must cache the new module');
assert.ok(html.includes('safety-sync.js?v=3.83-hotfix1'),'safety runtime must load');
assert.ok(!html.includes('NO EXTERNAL UPLINK'),'do not claim no network requests');
assert.ok(!html.includes('ENCRYPTED MESH TRAFFIC'),'unverified demo messages are not encrypted live traffic');
assert.ok(app.includes('Date.now()-lastFixAt<=60000'),'navigation requires a fresh fix');
const dom=new JSDOM(html,{url:'https://field.test/field-os/index.html',runScripts:'outside-only',pretendToBeVisual:true});
const w=dom.window,d=w.document;
let current={lat:44.4759,lon:-73.2121,alt:300,accuracy:4,source:'DEMO GNSS',updatedAt:Date.now()};
w.FIELD_MAP_DATA={current:()=>current};w.FIELD_RUNTIME={every:()=>()=>{}};
w.FIELD_MESH={state:{nodes:[]}};
w.FIELD_TRACK_STATUS=()=>({active:false,points:0,distanceMiles:0});
vm.runInContext(safety,dom.getInternalVMContext(),{filename:'safety-sync.js'});
assert.match(d.getElementById('sosPosition').textContent,/NO FIX/,'demo GPS must never show as real SOS coordinates');
assert.equal(d.getElementById('sensorIntegrityGnss').textContent,'UNKNOWN / NO FIX');
assert.equal(d.getElementById('homeTrackState').textContent,'STOPPED');
assert.equal(d.getElementById('meshCount').textContent,'—');
current={...current,source:'PHONE GNSS',accuracy:7,updatedAt:Date.now()};
w.FIELD_SAFETY.update();
assert.match(d.getElementById('sosPosition').textContent,/44.47590/);
assert.match(d.getElementById('sosGnss').textContent,/RECENT/);
assert.equal(d.getElementById('satCount').textContent,'FIX');
current={...current,updatedAt:Date.now()-180000};
w.FIELD_SAFETY.update();
assert.match(d.getElementById('sosPosition').textContent,/NO FIX/,'stale coordinates must not be emitted as verified');
w.localStorage.setItem('fieldos-v12-waypoints',JSON.stringify([{id:'1',name:'<img src=x onerror=alert(1)>',type:'BASE',lat:44.5,lon:-73.2}]));
w.FIELD_SAFETY.update();
assert.match(d.getElementById('homeWaypointRows').textContent,/<img/);
assert.equal(d.getElementById('homeWaypointRows').querySelector('img'),null,'untrusted waypoint labels must render as text');
assert.equal(d.getElementById('emergencyDial').getAttribute('href'),'#','dial link must not assume an emergency number');
w.close();
console.log('PASS safety defaults, demo/stale GNSS rejection, real fix binding, offline registration, HTML injection and region-aware emergency call');
