/* Reproducible, pinned, locally served map dependencies for airplane mode.
 * npm install --no-save --ignore-scripts --no-package-lock
 *   leaflet@1.9.4 pmtiles@4.5.0 protomaps-leaflet@5.1.0
 * node scripts/vendor-offline.cjs
 */
'use strict';
const fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..');
const vendored=[
 ['leaflet@1.9.4','leaflet','dist/leaflet.js','vendor/leaflet/leaflet.js',75000],
 ['leaflet@1.9.4','leaflet','dist/leaflet.css','vendor/leaflet/leaflet.css',7500],
 ['pmtiles@4.5.0','pmtiles','dist/pmtiles.js','vendor/pmtiles/pmtiles.js',25000],
 ['protomaps-leaflet@5.1.0','protomaps-leaflet','dist/protomaps-leaflet.js','vendor/protomaps-leaflet/protomaps-leaflet.js',40000]
];
const licenses=[];
for(const [label,packageName,src,dest,minBytes] of vendored){
 const pkg=path.join(root,'node_modules',packageName);
 const version=JSON.parse(fs.readFileSync(path.join(pkg,'package.json'),'utf8')).version;
 const required=label.split('@').at(-1);
 if(version!==required)throw Error('Refusing unpinned map dependency: '+label+' installed '+version);
 const from=path.join(pkg,src),to=path.join(root,dest);
 const size=fs.statSync(from).size;
 if(size<minBytes)throw Error('Unexpectedly small map library: '+from+' '+size);
 fs.mkdirSync(path.dirname(to),{recursive:true});
 fs.copyFileSync(from,to);
 console.log(dest+': '+size+' bytes');
 if(!licenses.includes(packageName))licenses.push(packageName);
}
const leafletImages=path.join(root,'node_modules/leaflet/dist/images');
for(const filename of ['marker-icon.png','marker-icon-2x.png','marker-shadow.png','layers.png','layers-2x.png']){
 const src=path.join(leafletImages,filename);
 const dest=path.join(root,'vendor/leaflet/images',filename);
 if(!fs.existsSync(src))throw Error('Missing Leaflet local image '+filename);
 fs.mkdirSync(path.dirname(dest),{recursive:true});
 fs.copyFileSync(src,dest);
}
const notices=[
 '# Offline map libraries — pinned source and licenses',
 '',
 'Generated by scripts/vendor-offline.cjs from official npm tarballs:',
 '- leaflet@1.9.4 (BSD-2-Clause)',
 '- pmtiles@4.5.0 (BSD-3-Clause)',
 '- protomaps-leaflet@5.1.0 (BSD-3-Clause)',
 '',
 'These are locally served by FIELD/OS for offline launch. They are not map',
 'coverage; users still need a saved regional PMTiles archive in IndexedDB.',
 '',
 'Original license texts follow.',''
];
for(const name of licenses){
 const dir=path.join(root,'node_modules',name);
 const filename=['LICENSE','LICENSE.md','LICENSE.txt'].find(f=>fs.existsSync(path.join(dir,f)));
 if(!filename)throw Error('Missing required attribution/license file for '+name);
 notices.push('## '+name+' / '+filename,'',fs.readFileSync(path.join(dir,filename),'utf8'),'');
}
fs.writeFileSync(path.join(root,'vendor','LICENSES.md'),notices.join('\n'));
